version: '3.5'

services:
  ai_service:
    build: .
    restart: on-failure
    env_file:
      - .env
    container_name: ${AI_SERVER_HOST}
    ports:
      - "${AI_SERVER_PORT}:${AI_SERVER_PORT}"
    networks:
      ai_chat-backend:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./ollama_data_docker:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      ai_chat-backend:

networks:
  ai_chat-backend:
    name: ai_chat-backend
    external: true
